# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/base_design/base_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_design || ORIG_REF_NAME==base_design} -quiet] -quiet

# IP: bd/base_design/ip/base_design_processing_system7_0_0/base_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_design_processing_system7_0_0 || ORIG_REF_NAME==base_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/base_design/ip/base_design_axi_gpio_0_0/base_design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_design_axi_gpio_0_0 || ORIG_REF_NAME==base_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/base_design/ip/base_design_ps7_0_axi_periph_0/base_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==base_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/base_design/ip/base_design_rst_ps7_0_50M_0/base_design_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==base_design_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/base_design/ip/base_design_auto_pc_0/base_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_design_auto_pc_0 || ORIG_REF_NAME==base_design_auto_pc_0} -quiet] -quiet

# XDC: bd/base_design/base_design_ooc.xdc
